# Generated by Django 2.0.1 on 2018-01-25 07:54

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('creator', models.CharField(max_length=100, verbose_name='Creator')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[130, 200], upload_to='', verbose_name='Image')),
            ],
            options={
                'permissions': (('manage_news', 'Manage_News'),),
            },
        ),
    ]
