# Generated by Django 2.0.1 on 2018-03-07 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180125_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='nop', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
