# Generated by Django 2.0.1 on 2018-03-09 07:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180307_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[130, 200], upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, help_text='Determines whether everyone sees the post. False: only admins.', verbose_name='Published'),
        ),
    ]
