# Generated by Django 2.0.1 on 2018-03-15 17:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180309_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 500], upload_to='', verbose_name='Image'),
        ),
    ]
