# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField(verbose_name='Name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('game_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.GameGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('playable', models.BooleanField(verbose_name='Playable')),
                ('missing_items', models.TextField(verbose_name='Missing items')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.GamePiece')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateTimeField(verbose_name='From')),
                ('date_to', models.DateTimeField(verbose_name='To')),
                ('status', models.IntegerField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', verbose_name='Status')),
                ('bail', models.TextField(verbose_name='Bail')),
                ('games', models.ManyToManyField(related_name='rents', to='web.GamePiece', verbose_name='Games')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('new_status', models.IntegerField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], verbose_name='Status')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Profile'),
        ),
        migrations.AddField(
            model_name='gamepiece',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.Profile', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Profile'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='games',
            field=models.ManyToManyField(related_name='packs', to='web.GameGroup'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Rent'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Profile'),
        ),
    ]
