# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='image',
            field=models.ImageField(default=' ', upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamegroup',
            name='short_description',
            field=models.TextField(default=' ', verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
