# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jhuser',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number for helping communication if necessery.', max_length=100, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='jhuser',
            name='room',
            field=models.CharField(blank=True, help_text='Room number.', max_length=100, verbose_name='room'),
        ),
    ]
