# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='image',
            field=models.ImageField(default='/default.png', upload_to='', verbose_name='Image'),
        ),
    ]
