# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171209_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gamegroup',
            name='short_description',
            field=models.CharField(max_length=100, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='gamepack',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='notes',
            field=models.CharField(max_length=100, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='missing_items',
            field=models.CharField(max_length=100, verbose_name='Missing items'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bail',
            field=models.CharField(max_length=30, verbose_name='Bail'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('inmyroom', 'In my room'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rentactions',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('inmyroom', 'In my room'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
