# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_gamegroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='short_description',
            field=models.TextField(default='non', verbose_name='Short Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamegroup',
            name='image',
            field=models.ImageField(default='../../site-media/neptun.png', upload_to='', verbose_name='Image'),
        ),
    ]
