# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171210_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepiece',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
