# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171210_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepack',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
