# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171210_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepiece',
            name='game_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pieces', to='web.GameGroup'),
        ),
    ]
