# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171210_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bail',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bail'),
        ),
    ]
