# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171211_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='web.Rent'),
        ),
    ]
