# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20171215_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('inmyroom', 'In my room'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='web.Rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rentactions',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='rentactions',
            name='user',
        ),
        migrations.DeleteModel(
            name='RentActions',
        ),
    ]
