# Generated by Django 2.0.1 on 2018-01-12 10:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180112_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[130, 100], upload_to='', verbose_name='Image'),
        ),
    ]
