# Generated by Django 2.0.1 on 2018-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180112_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepiece',
            name='rentable',
            field=models.BooleanField(default=True, verbose_name='Rentable'),
        ),
    ]
