# Generated by Django 2.0.1 on 2018-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_gamepiece_rentable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepiece',
            name='players',
            field=models.CharField(default='?', max_length=100, verbose_name='Players'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamepiece',
            name='playtime',
            field=models.CharField(default='0', max_length=100, verbose_name='Playing time'),
            preserve_default=False,
        ),
    ]
