# Generated by Django 2.0.1 on 2018-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180224_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepiece',
            name='rules',
            field=models.CharField(default='-', max_length=100, verbose_name='Rules'),
        ),
    ]
