# Generated by Django 2.0.1 on 2018-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_gamepiece_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepiece',
            name='rules',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rules',
            field=models.CharField(default='-', max_length=100, verbose_name='Rules'),
        ),
    ]
