# Generated by Django 2.0.1 on 2018-03-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180224_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='base_game',
            field=models.ForeignKey(blank=True, help_text='Game needed to play this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.GameGroup', verbose_name='Base game'),
        ),
    ]
