# Generated by Django 2.0.1 on 2018-03-27 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_gamegroup_base_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepiece',
            name='buying_date',
            field=models.DateField(blank=True, null=True, verbose_name='Buying date'),
        ),
        migrations.AddField(
            model_name='gamepiece',
            name='place',
            field=models.CharField(blank=True, max_length=20, verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='gamepiece',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Ft)'),
        ),
    ]
