# Generated by Django 2.0.1 on 2018-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180327_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepiece',
            name='notes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Notes'),
        ),
    ]
