# Generated by Django 2.0.1 on 2018-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180327_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='players',
            field=models.CharField(help_text='Example: 2 - 6', max_length=100, verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='gamegroup',
            name='playtime',
            field=models.CharField(help_text='Example: 20 mins', max_length=100, verbose_name='Playing time'),
        ),
    ]
