# Generated by Django 2.0.1 on 2018-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180328_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='hide',
            field=models.BooleanField(default=False, help_text="If true isn't shown in Our games page.", verbose_name='Hide from users'),
        ),
    ]
