# Generated by Django 2.0.1 on 2018-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20180603_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegroup',
            name='players',
        ),
    ]
