# Generated by Django 2.0.1 on 2018-06-03 23:04

from django.db import migrations, models
from inventory.models import GameGroup


def default_playtime_category(apps, schema_editor):
    """custom migration script to calculate default for playtime_category"""

    GameGroupM = apps.get_model('inventory', 'gamegroup')
    for g in GameGroupM.objects.all():
        # if playtime is not given leave it
        if g.playtime:
            try:
                value = int(g.playtime.replace("perc", "").split('-')[0].strip())

                if value <= 15:
                    g.playtime_category = GameGroup.LENGTH_SHORT[0]
                elif value <= 60:
                    g.playtime_category = GameGroup.LENGTH_MEDIUM[0]
                else:
                    g.playtime_category = GameGroup.LENGTH_LONG[0]
                g.save()
            except ValueError:
                print("%s skipped due to invalid playtime (%s)." % (g.name, g.playtime))
        else:
            print("%s skipped due to empty playtime." % g.name)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_gamegroup_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='playtime_category',
            field=models.CharField(choices=[('short', 'short (20 mins)'), ('medium', 'medium (20-60 mins)'), ('long', 'long (60+ mins)')], default='short', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.RunPython(default_playtime_category)
    ]
