# Generated by Django 2.0.1 on 2018-06-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_gamegroup_playtime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='playtime',
            field=models.CharField(help_text='Example: 20 mins (this is directly displayed to the user)', max_length=100, verbose_name='Playing time'),
        ),
        migrations.AlterField(
            model_name='gamegroup',
            name='playtime_category',
            field=models.CharField(choices=[('short', 'short (20 mins)'), ('medium', 'medium (20-60 mins)'), ('long', 'long (60+ mins)')], max_length=20, verbose_name='Playtime category'),
        ),
    ]
