# Generated by Django 2.2.19 on 2021-03-21 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20180604_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='description',
            field=models.TextField(help_text='Detailed description of the game, which is visible to the users.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gamegroup',
            name='hide',
            field=models.BooleanField(blank=True, default=False, help_text="If true isn't shown in Our games page.", verbose_name='Hide from users'),
        ),
        migrations.AlterField(
            model_name='gamegroup',
            name='short_description',
            field=models.CharField(help_text='Short description, which will show up in tooltips.', max_length=100, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='game_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pieces', to='inventory.GameGroup', verbose_name='Game group'),
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the game or empty if it belongs to the group.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='place',
            field=models.CharField(blank=True, help_text='Where the game should be.', max_length=20, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='If more then one game piece belongs to the game group, the one with lower priority will be rented first.', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='rentable',
            field=models.BooleanField(default=True, help_text='The game can only be rented if this option is true.', verbose_name='Rentable'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.GamePiece', verbose_name='Game piece'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='playable',
            field=models.BooleanField(help_text="If the game is still playable, so there's no major parts missing.", verbose_name='Playable'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
