# Generated by Django 2.2.24 on 2021-11-17 20:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210321_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, size=[130, 100], upload_to='', verbose_name='Image'),
        ),
    ]
