# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_from', models.DateTimeField(verbose_name='From')),
                ('date_to', models.DateTimeField(verbose_name='To')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('inmyroom', 'In my room'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('bail', models.CharField(blank=True, max_length=30, verbose_name='Bail')),
                ('games', models.ManyToManyField(related_name='rents', to='inventory.GamePiece', verbose_name='Games')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('manage_rents', 'Manage rents'), ('view_stat', 'View rent statistics')),
            },
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('gaveout', 'Gave out'), ('inmyroom', 'In my room'), ('back', 'Brought back'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='rent.Rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='rent.Rent'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
