# Generated by Django 2.0.1 on 2018-05-22 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0003_auto_20180522_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renthistory',
            name='notes',
        ),
        migrations.AddField(
            model_name='renthistory',
            name='new_renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='New renter'),
        ),
    ]
