# Generated by Django 2.0.1 on 2018-05-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_gamegroup_hide'),
        ('rent', '0004_auto_20180522_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='deleted_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.GamePiece', verbose_name='Deleted game piece'),
        ),
        migrations.AddField(
            model_name='renthistory',
            name='new_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.GamePiece', verbose_name='New game piece'),
        ),
    ]
