# Generated by Django 2.0.1 on 2018-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20180527_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='edited_date_from',
            field=models.DateTimeField(null=True, verbose_name='Edited from'),
        ),
        migrations.AddField(
            model_name='renthistory',
            name='edited_date_to',
            field=models.DateTimeField(null=True, verbose_name='Edited to'),
        ),
    ]
