# Generated by Django 2.0.1 on 2018-01-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jatszohaz', '0002_auto_20180112_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jhuser',
            options={'permissions': (('view_all', 'View all'),)},
        ),
    ]
