# Generated by Django 2.0.1 on 2018-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatszohaz', '0003_auto_20180124_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='jhuser',
            name='checked_profile',
            field=models.BooleanField(default=False, help_text='From time to time everyone is required to check his profile.', verbose_name='Checked profile'),
        ),
        migrations.AlterField(
            model_name='jhuser',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number for helping communication if necessary.', max_length=100, verbose_name='mobile'),
        ),
    ]
