# Generated by Django 2.0.1 on 2018-04-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jatszohaz', '0004_auto_20180303_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jhuser',
            options={'permissions': (('view_all', 'View all'), ('basic_admin', 'Basic admin rights'))},
        ),
    ]
