# Generated by Django 2.0.1 on 2018-05-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jatszohaz', '0006_auto_20180418_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jhuser',
            options={'ordering': ('last_name', 'first_name'), 'permissions': (('view_all', 'View all user details'), ('basic_admin', 'Basic admin rights'), ('leader_admin', 'Group leader rights'))},
        ),
    ]
