# Generated by Django 2.0.1 on 2018-05-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jatszohaz', '0007_auto_20180522_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jhuser',
            options={'ordering': ('last_name', 'first_name'), 'permissions': (('view_all', 'View all user details'), ('basic_admin', 'Basic admin rights'), ('view_user_stat', 'View statistics for users'), ('leader_admin', 'Group leader rights'))},
        ),
    ]
